/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KCGXrZOzxgd
 */
import { Button } from "@/components/ui/button";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { useNavigate } from "react-router-dom";

export function OrderDetails() {
  const navigate = useNavigate();
  return (
    <Card className="justify-center max-w-5xl mx-auto mt-16">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex flex-col">
            <h2 className="text-lg font-bold tracking-tight">Order Details</h2>
            <p className="text-sm font-medium leading-none text-gray-500">
              Order #{"12345"}
            </p>
          </div>
          <Button size="sm" variant="default">
            Print
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="space-y-2">
            <div className="flex flex-col space-y-1">
              <p className="text-sm font-medium text-gray-500">Customer</p>
              <p className="text-sm font-medium">Alice Johnson</p>
            </div>
            <div className="flex flex-col space-y-1">
              <p className="text-sm font-medium text-gray-500">Address</p>
              <p className="text-sm font-medium">
                123 Street Rd, Apt 104, Cityville, 54321
              </p>
            </div>
          </div>
          <div className="space-y-2">
            <div className="flex flex-col space-y-1">
              <p className="text-sm font-medium text-gray-500">
                Payment Method
              </p>
              <p className="text-sm font-medium">Mastercard ending in 4242</p>
            </div>
            <div className="flex flex-col space-y-1">
              <p className="text-sm font-medium text-gray-500">Order Status</p>
              <p className="text-sm font-medium">Shipped</p>
            </div>
          </div>
        </div>
        <div className="overflow-auto w-full max-h-[300px] border border-gray-200 rounded-lg">
          <table className="min-w-full">
            <thead>
              <tr>
                <th className="p-4 text-xs font-medium tracking-wide text-gray-500">
                  Items
                </th>
                <th className="p-4 text-xs font-medium tracking-wide text-gray-500">
                  Quantity
                </th>
                <th className="p-4 text-xs font-medium tracking-wide text-gray-500">
                  Price
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="divide-x divide-gray-200">
                <td className="p-4">{"Sweatshirt (product name)"}</td>
                <td className="p-4">x{"1"}</td>
                <td className="p-4">₹ {"59.99"}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div className="flex flex-col items-start justify-between space-y-2 md:flex-row md:items-center md:space-y-0">
          <div className="flex flex-col space-y-1">
            <p className="text-sm font-medium">Total</p>
            <p className="text-2xl font-bold">$114.92</p>
          </div>
          <Button
            onClick={() => {
              navigate("/home/order");
            }}
          >
            Back to Orders
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
